import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas

/-!
# Relative completion and canonical pair-core containment

This module isolates two finite-dimensional steps used by a two-anchor
relation supplier.

* A panel in a second kernel is complete as soon as its rank increment over a
  known first kernel attains an independently certified upper bound relative
  to the exact kernel intersection.
* A canonical core lies in every pair sum when each pair of its local cuts
  spans the core.  Equality then follows from an exact dimension upper bound.

Neither theorem assumes a probability distribution or identifies the
application-specific canonical core.
-/

namespace ProjectedKernelRigidity.RelativeAnchor

open Submodule

variable {F V J : Type*} [Field F] [AddCommGroup V] [Module F V]

/-- The pair core of a family of observer kernels.  Repeated pairs are
harmless; the proof-facing definition avoids choosing an order on labels. -/
def pairCore (K : J → Submodule F V) : Submodule F V :=
  ⨅ i, ⨅ j, ⨅ (_h : i ≠ j), K i ⊔ K j

theorem le_pairCore_iff (K : J → Submodule F V) (C : Submodule F V) :
    C ≤ pairCore K ↔ ∀ i j, i ≠ j → C ≤ K i ⊔ K j := by
  simp [pairCore]

/-- If every two distinct local cuts span the canonical core and each cut is
contained in its observer kernel, then the canonical core is contained in the
pair core. -/
theorem canonical_le_pairCore (K G : J → Submodule F V) (C : Submodule F V)
    (hcut : ∀ i, G i ≤ K i)
    (hspan : ∀ i j, i ≠ j → C ≤ G i ⊔ G j) :
    C ≤ pairCore K := by
  rw [le_pairCore_iff]
  intro i j hij
  exact (hspan i j hij).trans (sup_le_sup (hcut i) (hcut j))

/-- Canonical containment plus a dimension upper bound identifies the pair
core exactly.  This is the deterministic replacement for a favorable-rank
heuristic. -/
theorem pairCore_eq_of_canonical_le_of_finrank_le [FiniteDimensional F V]
    (K : J → Submodule F V) (C : Submodule F V)
    (hC : C ≤ pairCore K)
    (hdim : Module.finrank F (pairCore K) ≤ Module.finrank F C) :
    pairCore K = C := by
  exact (Submodule.eq_of_le_of_finrank_le hC hdim).symm

/-- Rank increments over `K₁` and over the exact intersection `K₁ ∩ K₂`
agree for every supplied panel `P ≤ K₂`.  The addition-only statement avoids
truncated natural-number subtraction. -/
theorem relative_rank_increment_identity [FiniteDimensional F V]
    (K₁ K₂ P : Submodule F V) (hP : P ≤ K₂) :
    Module.finrank F ↑(K₁ ⊔ P) + Module.finrank F ↑(K₁ ⊓ K₂) =
      Module.finrank F K₁ + Module.finrank F ↑((K₁ ⊓ K₂) ⊔ P) := by
  have hinf : K₁ ⊓ P = (K₁ ⊓ K₂) ⊓ P := by
    apply le_antisymm
    · exact le_inf (le_inf inf_le_left (inf_le_right.trans hP)) inf_le_right
    · exact le_inf (inf_le_left.trans inf_le_left) inf_le_right
  have h₁ := Submodule.finrank_sup_add_finrank_inf_eq K₁ P
  have h₂ := Submodule.finrank_sup_add_finrank_inf_eq (K₁ ⊓ K₂) P
  rw [← hinf] at h₂
  omega

/-- **Relative completion theorem.**

Let `I = K₁ ∩ K₂`, let `P ≤ K₂` be a replayed panel, and let `U` be an
independent upper bound on `dim K₂`.  If the measured rank increment of `P`
over `K₁` reaches `U - dim I` (written without subtraction), then `K₂` has
dimension exactly `U` and is generated by the known intersection together
with `P`.
-/
theorem relative_completion [FiniteDimensional F V]
    (K₁ K₂ P : Submodule F V) (U : ℕ)
    (hP : P ≤ K₂)
    (hupper : Module.finrank F K₂ ≤ U)
    (hmatch : Module.finrank F ↑(K₁ ⊔ P) + Module.finrank F ↑(K₁ ⊓ K₂) =
      Module.finrank F K₁ + U) :
    Module.finrank F K₂ = U ∧ K₂ = (K₁ ⊓ K₂) ⊔ P := by
  have hrel := relative_rank_increment_identity K₁ K₂ P hP
  have hIP : Module.finrank F ↑((K₁ ⊓ K₂) ⊔ P) = U := by
    omega
  have hle : (K₁ ⊓ K₂) ⊔ P ≤ K₂ :=
    sup_le inf_le_right hP
  have heq : (K₁ ⊓ K₂) ⊔ P = K₂ := by
    apply Submodule.eq_of_le_of_finrank_le hle
    exact hupper.trans_eq hIP.symm
  constructor
  · rw [← heq, hIP]
  · exact heq.symm

end ProjectedKernelRigidity.RelativeAnchor
